language: go
sudo: false
go:
  - 1.5
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
